# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/brennoc/catkin_ws/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/brennoc/catkin_ws/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	cd /home/brennoc/catkin_ws/src && $(CMAKE_COMMAND) -E cmake_progress_start /home/brennoc/catkin_ws/src/CMakeFiles /home/brennoc/catkin_ws/src/create_pointcloud/CMakeFiles/progress.marks
	cd /home/brennoc/catkin_ws/src && $(MAKE) -f CMakeFiles/Makefile2 create_pointcloud/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/brennoc/catkin_ws/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/brennoc/catkin_ws/src && $(MAKE) -f CMakeFiles/Makefile2 create_pointcloud/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/brennoc/catkin_ws/src && $(MAKE) -f CMakeFiles/Makefile2 create_pointcloud/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/brennoc/catkin_ws/src && $(MAKE) -f CMakeFiles/Makefile2 create_pointcloud/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/brennoc/catkin_ws/src && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
create_pointcloud/CMakeFiles/cloud_to_image.dir/rule:
	cd /home/brennoc/catkin_ws/src && $(MAKE) -f CMakeFiles/Makefile2 create_pointcloud/CMakeFiles/cloud_to_image.dir/rule
.PHONY : create_pointcloud/CMakeFiles/cloud_to_image.dir/rule

# Convenience name for target.
cloud_to_image: create_pointcloud/CMakeFiles/cloud_to_image.dir/rule
.PHONY : cloud_to_image

# fast build rule for target.
cloud_to_image/fast:
	cd /home/brennoc/catkin_ws/src && $(MAKE) -f create_pointcloud/CMakeFiles/cloud_to_image.dir/build.make create_pointcloud/CMakeFiles/cloud_to_image.dir/build
.PHONY : cloud_to_image/fast

# Convenience name for target.
create_pointcloud/CMakeFiles/criar_pointcloud.dir/rule:
	cd /home/brennoc/catkin_ws/src && $(MAKE) -f CMakeFiles/Makefile2 create_pointcloud/CMakeFiles/criar_pointcloud.dir/rule
.PHONY : create_pointcloud/CMakeFiles/criar_pointcloud.dir/rule

# Convenience name for target.
criar_pointcloud: create_pointcloud/CMakeFiles/criar_pointcloud.dir/rule
.PHONY : criar_pointcloud

# fast build rule for target.
criar_pointcloud/fast:
	cd /home/brennoc/catkin_ws/src && $(MAKE) -f create_pointcloud/CMakeFiles/criar_pointcloud.dir/build.make create_pointcloud/CMakeFiles/criar_pointcloud.dir/build
.PHONY : criar_pointcloud/fast

# Convenience name for target.
create_pointcloud/CMakeFiles/pointcloud_tf_broadcaster.dir/rule:
	cd /home/brennoc/catkin_ws/src && $(MAKE) -f CMakeFiles/Makefile2 create_pointcloud/CMakeFiles/pointcloud_tf_broadcaster.dir/rule
.PHONY : create_pointcloud/CMakeFiles/pointcloud_tf_broadcaster.dir/rule

# Convenience name for target.
pointcloud_tf_broadcaster: create_pointcloud/CMakeFiles/pointcloud_tf_broadcaster.dir/rule
.PHONY : pointcloud_tf_broadcaster

# fast build rule for target.
pointcloud_tf_broadcaster/fast:
	cd /home/brennoc/catkin_ws/src && $(MAKE) -f create_pointcloud/CMakeFiles/pointcloud_tf_broadcaster.dir/build.make create_pointcloud/CMakeFiles/pointcloud_tf_broadcaster.dir/build
.PHONY : pointcloud_tf_broadcaster/fast

src/cloud_to_image.o: src/cloud_to_image.cpp.o
.PHONY : src/cloud_to_image.o

# target to build an object file
src/cloud_to_image.cpp.o:
	cd /home/brennoc/catkin_ws/src && $(MAKE) -f create_pointcloud/CMakeFiles/cloud_to_image.dir/build.make create_pointcloud/CMakeFiles/cloud_to_image.dir/src/cloud_to_image.cpp.o
.PHONY : src/cloud_to_image.cpp.o

src/cloud_to_image.i: src/cloud_to_image.cpp.i
.PHONY : src/cloud_to_image.i

# target to preprocess a source file
src/cloud_to_image.cpp.i:
	cd /home/brennoc/catkin_ws/src && $(MAKE) -f create_pointcloud/CMakeFiles/cloud_to_image.dir/build.make create_pointcloud/CMakeFiles/cloud_to_image.dir/src/cloud_to_image.cpp.i
.PHONY : src/cloud_to_image.cpp.i

src/cloud_to_image.s: src/cloud_to_image.cpp.s
.PHONY : src/cloud_to_image.s

# target to generate assembly for a file
src/cloud_to_image.cpp.s:
	cd /home/brennoc/catkin_ws/src && $(MAKE) -f create_pointcloud/CMakeFiles/cloud_to_image.dir/build.make create_pointcloud/CMakeFiles/cloud_to_image.dir/src/cloud_to_image.cpp.s
.PHONY : src/cloud_to_image.cpp.s

src/criar_pointcloud.o: src/criar_pointcloud.cpp.o
.PHONY : src/criar_pointcloud.o

# target to build an object file
src/criar_pointcloud.cpp.o:
	cd /home/brennoc/catkin_ws/src && $(MAKE) -f create_pointcloud/CMakeFiles/criar_pointcloud.dir/build.make create_pointcloud/CMakeFiles/criar_pointcloud.dir/src/criar_pointcloud.cpp.o
.PHONY : src/criar_pointcloud.cpp.o

src/criar_pointcloud.i: src/criar_pointcloud.cpp.i
.PHONY : src/criar_pointcloud.i

# target to preprocess a source file
src/criar_pointcloud.cpp.i:
	cd /home/brennoc/catkin_ws/src && $(MAKE) -f create_pointcloud/CMakeFiles/criar_pointcloud.dir/build.make create_pointcloud/CMakeFiles/criar_pointcloud.dir/src/criar_pointcloud.cpp.i
.PHONY : src/criar_pointcloud.cpp.i

src/criar_pointcloud.s: src/criar_pointcloud.cpp.s
.PHONY : src/criar_pointcloud.s

# target to generate assembly for a file
src/criar_pointcloud.cpp.s:
	cd /home/brennoc/catkin_ws/src && $(MAKE) -f create_pointcloud/CMakeFiles/criar_pointcloud.dir/build.make create_pointcloud/CMakeFiles/criar_pointcloud.dir/src/criar_pointcloud.cpp.s
.PHONY : src/criar_pointcloud.cpp.s

src/pointcloud_tf_broadcaster.o: src/pointcloud_tf_broadcaster.cpp.o
.PHONY : src/pointcloud_tf_broadcaster.o

# target to build an object file
src/pointcloud_tf_broadcaster.cpp.o:
	cd /home/brennoc/catkin_ws/src && $(MAKE) -f create_pointcloud/CMakeFiles/pointcloud_tf_broadcaster.dir/build.make create_pointcloud/CMakeFiles/pointcloud_tf_broadcaster.dir/src/pointcloud_tf_broadcaster.cpp.o
.PHONY : src/pointcloud_tf_broadcaster.cpp.o

src/pointcloud_tf_broadcaster.i: src/pointcloud_tf_broadcaster.cpp.i
.PHONY : src/pointcloud_tf_broadcaster.i

# target to preprocess a source file
src/pointcloud_tf_broadcaster.cpp.i:
	cd /home/brennoc/catkin_ws/src && $(MAKE) -f create_pointcloud/CMakeFiles/pointcloud_tf_broadcaster.dir/build.make create_pointcloud/CMakeFiles/pointcloud_tf_broadcaster.dir/src/pointcloud_tf_broadcaster.cpp.i
.PHONY : src/pointcloud_tf_broadcaster.cpp.i

src/pointcloud_tf_broadcaster.s: src/pointcloud_tf_broadcaster.cpp.s
.PHONY : src/pointcloud_tf_broadcaster.s

# target to generate assembly for a file
src/pointcloud_tf_broadcaster.cpp.s:
	cd /home/brennoc/catkin_ws/src && $(MAKE) -f create_pointcloud/CMakeFiles/pointcloud_tf_broadcaster.dir/build.make create_pointcloud/CMakeFiles/pointcloud_tf_broadcaster.dir/src/pointcloud_tf_broadcaster.cpp.s
.PHONY : src/pointcloud_tf_broadcaster.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... cloud_to_image"
	@echo "... criar_pointcloud"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... pointcloud_tf_broadcaster"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... src/cloud_to_image.o"
	@echo "... src/cloud_to_image.i"
	@echo "... src/cloud_to_image.s"
	@echo "... src/criar_pointcloud.o"
	@echo "... src/criar_pointcloud.i"
	@echo "... src/criar_pointcloud.s"
	@echo "... src/pointcloud_tf_broadcaster.o"
	@echo "... src/pointcloud_tf_broadcaster.i"
	@echo "... src/pointcloud_tf_broadcaster.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/brennoc/catkin_ws/src && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

