set(_CATKIN_CURRENT_PACKAGE "create_pointcloud")
set(create_pointcloud_MAINTAINER "brennoc <brennoc@todo.todo>")
set(create_pointcloud_DEPRECATED "")
set(create_pointcloud_VERSION "0.0.0")
set(create_pointcloud_BUILD_DEPENDS "geometry_msgs" "laser_geometry" "roscpp" "sensor_msgs" "tf")
set(create_pointcloud_RUN_DEPENDS "geometry_msgs" "laser_geometry" "roscpp" "sensor_msgs" "tf")
set(create_pointcloud_BUILDTOOL_DEPENDS "catkin")